// Seed recipe catalog for PantryPilot.
// Tags used for filtering: vegetarian, vegan, glutenFree, dairyFree, nutFree, quick, budget
export const RECIPES = [
  {
    id: "chickpea-curry",
    name: "Weeknight Chickpea Curry",
    tags: ["vegetarian", "vegan", "glutenFree", "dairyFree", "nutFree", "budget"],
    prepMinutes: 25,
    servings: 4,
    costPerServing: 2.1,
    nutrition: { calories: 420, proteinG: 14, carbsG: 58, fatG: 14 },
    ingredients: [
      { name: "chickpeas (canned)", qty: 2, unit: "can" },
      { name: "onion", qty: 1, unit: "pcs" },
      { name: "garlic", qty: 3, unit: "clove" },
      { name: "canned tomatoes", qty: 1, unit: "can" },
      { name: "coconut milk", qty: 1, unit: "can" },
      { name: "curry powder", qty: 2, unit: "tbsp" },
      { name: "rice", qty: 2, unit: "cup" },
    ],
    instructions: [
      "Saute onion and garlic in oil until soft.",
      "Add curry powder, tomatoes, and chickpeas; simmer 10 min.",
      "Stir in coconut milk, simmer 5 more minutes.",
      "Serve over rice.",
    ],
  },
  {
    id: "veggie-stirfry",
    name: "Sesame Veggie Stir-Fry",
    tags: ["vegetarian", "vegan", "dairyFree", "quick", "budget"],
    prepMinutes: 15,
    servings: 3,
    costPerServing: 2.4,
    nutrition: { calories: 380, proteinG: 11, carbsG: 45, fatG: 16 },
    ingredients: [
      { name: "broccoli", qty: 1, unit: "head" },
      { name: "carrot", qty: 2, unit: "pcs" },
      { name: "bell pepper", qty: 1, unit: "pcs" },
      { name: "soy sauce", qty: 3, unit: "tbsp" },
      { name: "sesame oil", qty: 1, unit: "tbsp" },
      { name: "peanuts", qty: 0.25, unit: "cup" },
      { name: "rice", qty: 1.5, unit: "cup" },
    ],
    instructions: [
      "Chop vegetables into bite-size pieces.",
      "Stir-fry over high heat 5-7 minutes.",
      "Add soy sauce and sesame oil, toss.",
      "Top with peanuts, serve over rice.",
    ],
  },
  {
    id: "lentil-soup",
    name: "Hearty Lentil Soup",
    tags: ["vegetarian", "vegan", "glutenFree", "dairyFree", "nutFree", "budget"],
    prepMinutes: 35,
    servings: 6,
    costPerServing: 1.6,
    nutrition: { calories: 260, proteinG: 15, carbsG: 40, fatG: 4 },
    ingredients: [
      { name: "lentils", qty: 2, unit: "cup" },
      { name: "onion", qty: 1, unit: "pcs" },
      { name: "carrot", qty: 2, unit: "pcs" },
      { name: "celery", qty: 2, unit: "stalk" },
      { name: "vegetable broth", qty: 6, unit: "cup" },
      { name: "canned tomatoes", qty: 1, unit: "can" },
    ],
    instructions: [
      "Saute onion, carrot, celery until soft.",
      "Add lentils, tomatoes, and broth.",
      "Simmer 25 minutes until lentils are tender.",
    ],
  },
  {
    id: "chicken-tacos",
    name: "Weeknight Chicken Tacos",
    tags: ["glutenFree", "dairyFree", "nutFree", "quick"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 3.2,
    nutrition: { calories: 410, proteinG: 30, carbsG: 32, fatG: 16 },
    ingredients: [
      { name: "chicken breast", qty: 500, unit: "g" },
      { name: "taco shells", qty: 8, unit: "pcs" },
      { name: "lettuce", qty: 1, unit: "head" },
      { name: "tomato", qty: 2, unit: "pcs" },
      { name: "lime", qty: 1, unit: "pcs" },
      { name: "taco seasoning", qty: 1, unit: "packet" },
    ],
    instructions: [
      "Season and cook diced chicken until browned.",
      "Warm taco shells.",
      "Assemble with lettuce, tomato, and a squeeze of lime.",
    ],
  },
  {
    id: "salmon-veggies",
    name: "Sheet-Pan Salmon & Veggies",
    tags: ["glutenFree", "dairyFree", "nutFree"],
    prepMinutes: 30,
    servings: 2,
    costPerServing: 6.5,
    nutrition: { calories: 430, proteinG: 34, carbsG: 12, fatG: 27 },
    ingredients: [
      { name: "salmon fillet", qty: 2, unit: "pcs" },
      { name: "asparagus", qty: 1, unit: "bunch" },
      { name: "cherry tomatoes", qty: 1, unit: "cup" },
      { name: "olive oil", qty: 2, unit: "tbsp" },
      { name: "lemon", qty: 1, unit: "pcs" },
    ],
    instructions: [
      "Arrange salmon and vegetables on a sheet pan.",
      "Drizzle with olive oil, season.",
      "Roast at 400F for 15-18 minutes.",
      "Finish with fresh lemon.",
    ],
  },
  {
    id: "caprese-pasta",
    name: "Caprese Pasta",
    tags: ["vegetarian", "nutFree", "quick"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 2.9,
    nutrition: { calories: 520, proteinG: 20, carbsG: 62, fatG: 20 },
    ingredients: [
      { name: "pasta", qty: 400, unit: "g" },
      { name: "cherry tomatoes", qty: 2, unit: "cup" },
      { name: "mozzarella", qty: 200, unit: "g" },
      { name: "basil", qty: 1, unit: "bunch" },
      { name: "olive oil", qty: 3, unit: "tbsp" },
      { name: "garlic", qty: 2, unit: "clove" },
    ],
    instructions: [
      "Cook pasta until al dente.",
      "Toss with halved tomatoes, torn mozzarella, basil, garlic, and olive oil.",
    ],
  },
  {
    id: "black-bean-bowl",
    name: "Black Bean & Quinoa Bowl",
    tags: ["vegetarian", "vegan", "glutenFree", "dairyFree", "nutFree", "quick", "budget"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 2.0,
    nutrition: { calories: 390, proteinG: 15, carbsG: 60, fatG: 10 },
    ingredients: [
      { name: "quinoa", qty: 1.5, unit: "cup" },
      { name: "black beans (canned)", qty: 2, unit: "can" },
      { name: "corn", qty: 1, unit: "cup" },
      { name: "avocado", qty: 1, unit: "pcs" },
      { name: "lime", qty: 1, unit: "pcs" },
      { name: "cilantro", qty: 1, unit: "bunch" },
    ],
    instructions: [
      "Cook quinoa according to package directions.",
      "Warm black beans and corn.",
      "Assemble bowls, top with avocado, lime, and cilantro.",
    ],
  },
  {
    id: "beef-stirfry",
    name: "Ginger Beef Stir-Fry",
    tags: ["dairyFree", "nutFree", "quick"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 4.1,
    nutrition: { calories: 480, proteinG: 32, carbsG: 40, fatG: 20 },
    ingredients: [
      { name: "beef strips", qty: 450, unit: "g" },
      { name: "broccoli", qty: 1, unit: "head" },
      { name: "ginger", qty: 1, unit: "tbsp" },
      { name: "garlic", qty: 2, unit: "clove" },
      { name: "soy sauce", qty: 3, unit: "tbsp" },
      { name: "rice", qty: 2, unit: "cup" },
    ],
    instructions: [
      "Sear beef strips until browned, set aside.",
      "Stir-fry broccoli with ginger and garlic.",
      "Combine with beef and soy sauce, serve over rice.",
    ],
  },
  {
    id: "veggie-omelette",
    name: "Veggie Omelette",
    tags: ["vegetarian", "glutenFree", "nutFree", "quick", "budget"],
    prepMinutes: 12,
    servings: 2,
    costPerServing: 1.8,
    nutrition: { calories: 320, proteinG: 22, carbsG: 8, fatG: 22 },
    ingredients: [
      { name: "eggs", qty: 6, unit: "pcs" },
      { name: "bell pepper", qty: 1, unit: "pcs" },
      { name: "spinach", qty: 1, unit: "cup" },
      { name: "cheddar cheese", qty: 0.5, unit: "cup" },
      { name: "onion", qty: 0.5, unit: "pcs" },
    ],
    instructions: [
      "Whisk eggs, pour into a hot pan.",
      "Add sauteed vegetables and cheese, fold.",
    ],
  },
  {
    id: "thai-peanut-noodles",
    name: "Thai Peanut Noodles",
    tags: ["vegetarian", "dairyFree", "quick"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 2.6,
    nutrition: { calories: 460, proteinG: 14, carbsG: 58, fatG: 18 },
    ingredients: [
      { name: "rice noodles", qty: 300, unit: "g" },
      { name: "peanut butter", qty: 0.33, unit: "cup" },
      { name: "soy sauce", qty: 3, unit: "tbsp" },
      { name: "lime", qty: 1, unit: "pcs" },
      { name: "carrot", qty: 2, unit: "pcs" },
      { name: "peanuts", qty: 0.25, unit: "cup" },
    ],
    instructions: [
      "Cook noodles, drain.",
      "Whisk peanut butter, soy sauce, and lime into a sauce.",
      "Toss noodles with sauce, shredded carrot, and peanuts.",
    ],
  },
  {
    id: "margherita-pizza",
    name: "Homemade Margherita Pizza",
    tags: ["vegetarian", "nutFree"],
    prepMinutes: 40,
    servings: 4,
    costPerServing: 2.7,
    nutrition: { calories: 470, proteinG: 19, carbsG: 55, fatG: 18 },
    ingredients: [
      { name: "pizza dough", qty: 1, unit: "pcs" },
      { name: "canned tomatoes", qty: 1, unit: "can" },
      { name: "mozzarella", qty: 250, unit: "g" },
      { name: "basil", qty: 1, unit: "bunch" },
      { name: "olive oil", qty: 2, unit: "tbsp" },
    ],
    instructions: [
      "Spread crushed tomatoes on stretched dough.",
      "Top with mozzarella.",
      "Bake at 475F for 12-15 minutes, finish with basil and olive oil.",
    ],
  },
  {
    id: "shrimp-fajitas",
    name: "Shrimp Fajitas",
    tags: ["glutenFree", "dairyFree", "nutFree", "quick"],
    prepMinutes: 20,
    servings: 4,
    costPerServing: 4.4,
    nutrition: { calories: 400, proteinG: 28, carbsG: 38, fatG: 14 },
    ingredients: [
      { name: "shrimp", qty: 500, unit: "g" },
      { name: "bell pepper", qty: 2, unit: "pcs" },
      { name: "onion", qty: 1, unit: "pcs" },
      { name: "corn tortillas", qty: 8, unit: "pcs" },
      { name: "lime", qty: 1, unit: "pcs" },
      { name: "fajita seasoning", qty: 1, unit: "packet" },
    ],
    instructions: [
      "Saute peppers and onion until charred.",
      "Add shrimp and seasoning, cook until pink.",
      "Serve in warm tortillas with lime.",
    ],
  },
  {
    id: "mushroom-risotto",
    name: "Creamy Mushroom Risotto",
    tags: ["vegetarian", "glutenFree", "nutFree"],
    prepMinutes: 40,
    servings: 4,
    costPerServing: 3.3,
    nutrition: { calories: 440, proteinG: 12, carbsG: 60, fatG: 16 },
    ingredients: [
      { name: "arborio rice", qty: 1.5, unit: "cup" },
      { name: "mushrooms", qty: 300, unit: "g" },
      { name: "vegetable broth", qty: 5, unit: "cup" },
      { name: "parmesan", qty: 0.5, unit: "cup" },
      { name: "onion", qty: 1, unit: "pcs" },
      { name: "butter", qty: 2, unit: "tbsp" },
    ],
    instructions: [
      "Saute onion and mushrooms in butter.",
      "Add rice, toast briefly.",
      "Stir in warm broth a ladle at a time until creamy.",
      "Finish with parmesan.",
    ],
  },
  {
    id: "turkey-chili",
    name: "One-Pot Turkey Chili",
    tags: ["glutenFree", "dairyFree", "nutFree", "budget"],
    prepMinutes: 35,
    servings: 6,
    costPerServing: 2.5,
    nutrition: { calories: 350, proteinG: 28, carbsG: 30, fatG: 12 },
    ingredients: [
      { name: "ground turkey", qty: 500, unit: "g" },
      { name: "kidney beans (canned)", qty: 2, unit: "can" },
      { name: "canned tomatoes", qty: 2, unit: "can" },
      { name: "onion", qty: 1, unit: "pcs" },
      { name: "chili powder", qty: 2, unit: "tbsp" },
      { name: "garlic", qty: 2, unit: "clove" },
    ],
    instructions: [
      "Brown turkey with onion and garlic.",
      "Add beans, tomatoes, and chili powder.",
      "Simmer 20 minutes.",
    ],
  },
  {
    id: "greek-salad-pita",
    name: "Greek Salad Pitas",
    tags: ["vegetarian", "nutFree", "quick"],
    prepMinutes: 15,
    servings: 3,
    costPerServing: 2.8,
    nutrition: { calories: 380, proteinG: 13, carbsG: 42, fatG: 17 },
    ingredients: [
      { name: "pita bread", qty: 3, unit: "pcs" },
      { name: "cucumber", qty: 1, unit: "pcs" },
      { name: "tomato", qty: 2, unit: "pcs" },
      { name: "feta cheese", qty: 150, unit: "g" },
      { name: "kalamata olives", qty: 0.5, unit: "cup" },
      { name: "olive oil", qty: 2, unit: "tbsp" },
    ],
    instructions: [
      "Chop cucumber and tomato, toss with feta, olives, and olive oil.",
      "Stuff into warmed pitas.",
    ],
  },
  {
    id: "tofu-curry",
    name: "Red Tofu Curry",
    tags: ["vegetarian", "vegan", "glutenFree", "dairyFree", "nutFree"],
    prepMinutes: 25,
    servings: 4,
    costPerServing: 2.7,
    nutrition: { calories: 400, proteinG: 16, carbsG: 38, fatG: 20 },
    ingredients: [
      { name: "tofu", qty: 400, unit: "g" },
      { name: "coconut milk", qty: 1, unit: "can" },
      { name: "red curry paste", qty: 2, unit: "tbsp" },
      { name: "bell pepper", qty: 1, unit: "pcs" },
      { name: "rice", qty: 2, unit: "cup" },
    ],
    instructions: [
      "Pan-sear cubed tofu until golden.",
      "Simmer curry paste with coconut milk, add pepper and tofu.",
      "Serve over rice.",
    ],
  },
];

export function findRecipeById(id) {
  return RECIPES.find((r) => r.id === id) || null;
}
